name: Validate Theme

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install -g @vscode/vsce
        npm install -g jsonlint
    
    - name: Validate JSON files
      run: |
        set -e
        echo "Validating theme JSON files..."
        jsonlint themes/ib-theme-dark.json || { echo "Error: Dark theme JSON validation failed"; exit 1; }
        jsonlint themes/ib-theme-light.json || { echo "Error: Light theme JSON validation failed"; exit 1; }
        echo "JSON validation passed!"
    
    - name: Validate package.json
      run: |
        set -e
        echo "Validating package.json..."
        jsonlint package.json || { echo "Error: package.json validation failed"; exit 1; }
        echo "package.json validation passed!"
    
    - name: Package extension
      run: |
        set -e
        echo "Packaging extension..."
        vsce package --no-yarn || { echo "Error: Extension packaging failed"; exit 1; }
        echo "Extension packaged successfully!"
    
    - name: Check file sizes
      run: |
        set -e
        echo "Checking theme file sizes..."
        ls -la themes/ || { echo "Error: Cannot list theme files"; exit 1; }
        echo "Package size:"
        ls -la *.vsix || { echo "Error: Cannot find packaged extension"; exit 1; } 